name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up System
      run: |
        sudo apt install libsqlite3-dev
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Set up Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: git submodule
      run: |
        git submodule update --init
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bin/rails app:yarn:install
    - name: Prepare DB
      run: |
        bin/rails db:drop
        bin/rails db:create
        bin/rails db:migrate
    - name: Run test
      run: |
        bin/rails test
